# Generated by Django 5.1.4 on 2024-12-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
