# Generated by Django 5.1.4 on 2024-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
